#!/bin/zsh

. Vglobals

echo "checking for updates in AUR...";

cur_dir=$PWD;

for pac in $(ls $AUR_GIT_FOLDER); do
	echo $pac;
	cd $AUR_GIT_FOLDER/$pac;
	git pull;
done

cd $cur_dir;

echo -e "\nfinito)";
