#!/bin/zsh

. Vglobals

echo "checking for updates in AUR...";

cur_dir=$PWD;

for pac in $(ls $AUR_GIT_FOLDER); do
	echo -e "\n$pac";
	cd $AUR_GIT_FOLDER/$pac;
	response="$(git pull)";
	echo "$response";
	if [ "$response" = "Already up to date." ]; then
		echo "nothing to do";
	else
		git log --all --oneline -n 5;
 		makepkg --noconfirm -sic;
		echo -e "\n\n";		
	fi
done

cd $cur_dir;

echo -e "\nfinito)";
