#!/bin/zsh
. Vglobals.sh

function modify_interface_in_target()
{
	target="/etc/netctl/olga_sh";
	echo "setting interface in target profile $target to $1";
	sed -i 's/\(^ *Interface=\).*$/\1'"$1"'/' "$target";

	if [ $? -ne 0 ]; then
		echo "error while setting interface in target profile $target";
		exit 1;
	fi

	echo "target successfully changed";
}

function interface_status()
{
	echo "status:";
	ip link show "$1" | sed -n 's/.*\(<.*>\).*$/\1/p';	
}

function interface_mac()
{
	ip link show "$1" | grep ether | awk -F' ' '{ printf "current MAC:\n%s\n", $2 }'; 
}

# arg1 name of external card interface
function print_cards()
{
	echo -e "\nregular interface: $BUILT_IN_INTERFACE";
	interface_status "$BUILT_IN_INTERFACE";
	interface_mac "$BUILT_IN_INTERFACE";
	
	echo -e "\nextreme interface: $1";
	interface_status "$1";
	interface_mac "$1";	
}

function stop_network_services()
{
	systemctl stop netctl-auto@"$1";
}

function start_network_services()
{
	systemctl start netctl-auto@"$1";
}

function revert_mac()
{
	ip link set dev "$1" address $(macchanger -s "$1" | awk -F' ' '/Permanent/ {print $3}');
}

function change_address()
{
	if [ $# -ne 2 ]; then
		echo "invalid call to change_address, parameters must be: (interface_name, mode)";
		exit 1;
	fi

	ip link set "$1" down;
	if [ "$2" = "default" ]; then
		revert_mac "$1";
	else
		ip link set dev "$1" address "$2";	
	fi
}

# BEGIN
# Check arguments
if [[ ( $# -ne 1 ) || ( "$1" != "home" && "$1" != "xiaomi" && "$1" != "acer" ) ]]; then
	echo "must be one argument: home || xiaomi || acer";
	exit 1;
fi

xiaomi_mac="70:3a:51:3b:d0:85";
acer_mac="74:df:bf:81:81:db";

# find external interface
extreme_interface="$(PICK_WIRELESS_INTERFACE ext)";
if [ "$extreme_interface" = "NULL" ]; then
	echo "external interface not found";
	exit 1;
fi

echo "found external interface $extreme_interface";


if [ "$1" = "home" ]; then
	echo "she came back";
	stop_network_services "$extreme_interface";
	change_address "$extreme_interface" "default";
	start_network_services "$BUILT_IN_INTERFACE";
else
	if [ "$1" = "xiaomi" ]; then
		echo "switching to xiaomi";
		mac="$xiaomi_mac";
	elif [ "$1" = "acer" ]; then
		echo "switching to acer";
		mac="$acer_mac";
	else
		echo "unexpected situation";
		exit 1;
	fi

	stop_network_services "$BUILT_IN_INTERFACE";
	change_address "$extreme_interface" "$mac";
	modify_interface_in_target "$extreme_interface";
	start_network_services "$extreme_interface";
fi

print_cards $extreme_interface;

exit 0;

