#!/bin/zsh

#max size to transfer from computer in gigabytes
transfer_limit=10;

function foldername()
{
	echo "$1" | awk -F'/' 'BEGIN{OFS=FS}{$NF=""; print $0}';
}

#arg1 local directory
#arg2 android directory
function sync()
{
	if [ $# -ne 2 ]; then
		echo "2 arguements must be provided for sync";
		exit 3;
	fi

	if ! aft-mtp-cli "ls $2" > /dev/null; then
		exit 2;
	fi

	if [ -d "$1" ] && [ -O "$1" ] && [ -w "$1" ]; then
		echo "local directory exists with sufficient permissions";
	else
		echo "either local directory doesn't exist, or permissions aren't sufficient";
		exit 1;
	fi

	if [ "$(du -s $1 | head -n1 | awk '{print $1}')" -gt $((transfer_limit * 1000000)) ]; then
		echo "local folder is too large, you have probably made a mistake, and i have probably saved you))";
		exit 6;
	fi

	echo "device is connected and both folders are real";
	echo "synchronizing...";

	curr_dir="$pwd";
	cd "$1";
	find . -type f | cut -d'/' -f2- | sort > /tmp/status_local;
	aft-mtp-cli "ls-r $2" | sed -e 's/[0-9]\+ *//' | grep "\." | sort > /tmp/status_android;

	comm -3 --output-delimiter="~" /tmp/status_local /tmp/status_android > /tmp/status_common;

	local folder;
	# lines beginning with ~ are only on android
	echo "only on android:";
	for file in $(cat /tmp/status_common | grep "^~" | sed 's/^~//'); do
		folder="$(foldername $file)";
		echo "$file~~~$folder~~~";
		if [ -n "$folder" ] && [ ! -d "$folder" ]; then
			echo "creating local directory $folder";
			mkdir -p "$folder";
		fi	

		aft-mtp-cli "get $2/$file $file";
	done
	
	# lines not beginning with ~ are only on this pc
	echo "only on $HOST:";
	for file in $(cat /tmp/status_common | grep -v "^~"); do
		folder="$(foldername $file)";
		echo "$file~~~$folder~~~";
		if [ -n $folder ]; then
			aft-mtp-cli "mkpath $2/$folder";
		fi

		aft-mtp-cli "put $file $2/$folder";
	done



	rm /tmp/status_local;
	rm /tmp/status_android;
	rm /tmp/status_common;
	cd "$curr_dir";
}


if [ $# -lt 2 ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
	echo "Vandroidsync utility";
	echo "synchronizes directories on this machine and android device via USB";
	echo "at the end of process 2 directories will have same structure, and will";
	echo "contain same files";
	echo "doesn't delete files, if you want to - you'll have to do it manually on both devices";
	echo "(there is a reason behind this)";
	echo "if a local directory is larger then $transfer_limit gigabytes, utility will suppose";
	echo "you've chosen local directory by mistake and do nothing.";
	echo "if you want to make a larger transfer - change \$transfer_limit variable on top of"
	echo "the script\n";
	echo "usage: Vandroidsync <local directory> <android directory>"
	exit 0;
fi;

sync "$1" "$2";
