#!/bin/zsh

interface="null";
interfaces=($(ip link show | grep -e "^[1-9]\+" | cut -d ' ' -f 2 | tr ':' '\0'));
for i in $interfaces; do
	if [ "$1" = "$i" ]; then
		interface="$1";
		break;
	fi
done

if [ "$interface" = "null" ]; then
	echo "specified interface doesn't exist";
	exit 1;
fi

echo "Access point will be created on $interface";
sudo create_ap --mac f8:1a:67:af:1b:c3 --hidden "$interface" "$interface" gringo G350nslz831rV;

exit 0;
