#!/bin/zsh

function power_status()
{
	bluetoothctl show | grep Powered | tr '\t' ' ' | sed 's/^ \+//' | cut -d ' ' -f 2
}

. Vlib.sh

if [ $(power_status) = "yes" ]; then
	bluetoothctl power off;
else
	bluetoothctl power on;
fi

NOTIFY_FULL "bluetooth power: $(power_status)";
	

	

