#!/bin/zsh

function power_status()
{
	bluetoothctl show | grep Powered | tr '\t' ' ' | sed 's/^ \+//' | cut -d ' ' -f 2
}

. Vlib.sh

if [ "$#" -gt 0 ] && [ "$1" = "info" ]; then
	echo 'Host info:'
	bluetoothctl show | grep -e Alias -e Powered -e Discovering

	echo -e '\nPaired devices:'
	for mac in $(bluetoothctl paired-devices | awk '{print $2}'); do
		info="$(bluetoothctl info $mac)"
		echo $info | grep -e Alias -e Connected
		echo
	done

	exit 0
fi

if [ $(power_status) = "yes" ]; then
	bluetoothctl power off;
else
	bluetoothctl power on;
fi

NOTIFY_FULL "bluetooth power: $(power_status)";
	

	

