#!/bin/zsh

usefile="$HOME/Documents/oldschool/Database.kdbx";

backupdir="/opt/scripts/backup/keepass";
backup="$backupdir/Database_backup.kdbx";

networkfile="Database_net.kdbx";
networkdir="$HOME/Downloads";

if ! [ -e $backupdir ] || ! [ -e $usefile ]; then
	echo "backup directory or main use file don't exist";
	exit 1;
fi

# keep old backup backed up
cp $backup $backup.old;
echo "backup backed up)";
cp $usefile $backup;
echo "currently used file is backed up";


# obtain file from network

if ! [ -e "$networkdir/$networkfile" ]; then
	echo "network file doesn't exist";
else
	echo "merging network file to local backup...";
	cp "$networkdir/$networkfile" "$backupdir/$networkfile.old";
	keepassxc-cli merge -s $backup "$networkdir/$networkfile";
	# now backup file has all changes
	
	cp $backup "$networkdir/$networkfile";
	# send network file back to online storage
	# rm "$networkdir/$networkfile"
	
	cp $backup $usefile;
fi

echo "done";

