#!/bin/zsh

usefile="$HOME/Documents/oldschool/Database.kdbx";

backupdir="/opt/scripts/backup/keepass";
backup="$backupdir/Database_backup.kdbx";
network="$backupdir/Database_net.kdbx";

if ! [ -e $backupdir ] || ! [ -e $usefile ]; then
	echo "backup directory or main use file don't exist";
	exit 1;
fi

# keep old backup backed up
cp $backup $backup.old;
echo "backup backed up)";
cp $usefile $backup;
echo "currently used file is backed up";


# obtain file from network

if ! [ -e $network ]; then
	echo "network file doesn't exist";
else
	echo "merging network file to local backup...";
	cp $network $network.old;
	keepassxc-cli merge -s $backup $network;
	# now backup file has all changes
	cp $backup $network;

	# send network file back to online storage
	# rm $network
	
	cp $backup $usefile;
fi

echo "done";

