#!/bin/zsh

. Vglobals

if [ "$#" -gt 0 ]; then
	mode="$1";
else
	mode="$SCREENSHOTS_DEFAULT_MODE";
fi

if ! [ -d "$SCREENSHOTS_FOLDER" ]; then
	mkdir -p "$SCREENSHOTS_FOLDER";
	if ! [ -d "$SCREENSHOTS_FOLDER" ]; then
		echo "no screenshots folder";
		exit 1;
	fi
fi

filename="$SCREENSHOTS_FOLDER/$(date +'%Y.%m.%d_%H:%M:%S').png";

case "$mode" in
	"focused")
		scrot -u "$filename";
		;;
	"full")
		scrot "$filename";
		;;
	"select")
		scrot -s -f "$filename";
		;;
	*)
		echo "wrong argument";
		exit 1;
esac

xclip -selection c -t image/png < "$filename";
paplay /usr/share/sounds/freedesktop/stereo/screen-capture.oga;

