#!/bin/zsh
. Vlib.sh

cache="$(REQUIRE_CACHE vscreentoggle)";
turned=$(cat $cache);
if [ $turned = "1" ]; then
	xrandr --output DP-1 --off;
	echo 0 > $cache;
else
	xrandr --output DP-1 --auto;
	echo 1 > $cache;
	echo 'awesome.restart()' | awesome-client;
fi

