#!/bin/zsh

if [ "$#" -gt "0" ] && [ "$1" = "stop" ]; then
	if ps -e | grep -q x11vnc; then
		x11vnc -R stop;
	else
		echo "there is no x11vnc instance running";
		exit 1;
	fi
	exit 0;
fi

# check if vnc is not already running
if ps -e | grep -q x11vnc; then
	echo "VNC is already running";
	exit 1;
fi

echo "starting vnc server";

x11vnc -display :0 -nevershared -forever -rfbauth $HOME/.vnc/passwd -o /var/log/x11vnc.log;

exit 0;

