#!/bin/zsh

. Vglobals

if [ "$#" -ne "1" ]; then 
	echo "argument must be +, -, % or number (0 mutes and unmutes)";
	exit 1;
fi

working_sink="$(pactl list sinks short | awk '/bluez/{print $2}')";
if ! pactl list sinks short | grep -q "bluez"; then
	working_sink="$(pactl list sinks short | head -n1 | awk '{print $2}')";
fi

if [ "$1" = "0" ]; then
	pactl set-sink-mute $working_sink toggle;
elif [ "$1" = "+" ]; then
	pactl set-sink-volume $working_sink +$VOLUME_DERIVATIVE_SLOPE%;
elif [ "$1" = "-" ]; then
	pactl set-sink-volume $working_sink -$VOLUME_DERIVATIVE_SLOPE%;
elif [ "$1" = "%" ]; then
	echo "\tworking sink: $working_sink";
	pactl list sinks | grep -A10 $working_sink | grep -i -e "Volume: " -e "Mute: ";
elif [[ "$1" =~ "^[0-9]+$" ]]; then
	if (( $1 > 0 && $1 < 100)); then
		pactl set-sink-volume $working_sink $1%;
	else
		echo "volume must be between $min_volume and $max_volume";	
	fi
else 
	echo "argument must be +, -, % or number (0 mutes and unmutes)";
	exit 3;
fi

exit 0;

